### PR TITLE
Update npm modules and add Coverage

### PR DESCRIPTION
**Pull request by leobalter**

### CODE REVIEW

**Comment by mgol** [comment]
Looks good, though it'd be nice to have coverage state tracked in CI.

**Comment by leobalter** [comment]
>  it'd be nice to have coverage state tracked in CI. 

it's currently only reported on Travis, but we can add it later with any other tool like Coveralls or manually.

Can we do this on a follow up PR?

**Comment by leobalter** [comment]
the branch is rebased to remove conflicts, no changes were made in the contents of this PR.

**Comment by leobalter** [comment]
Apparently browserstack is failing for PRs but still passing on master. 

...

**Comment by mgol** [comment]
This looks good then once CI is fixed for PRs.

**Comment by leobalter** [comment]
I removed the coverage part as grunt-qunit-istanbul is triggering a failure on Mac OS Sierra, I need to update this module.

I'll fix the CI run and get this up to date

**Pull request merged**
