### PR TITLE
Readme: change CI badge for TravisCI

### PR DESCRIPTION
**Pull request by raphamorim**

### CODE REVIEW

**Comment by mgol** [comment]
Thanks for the PR.

Why should we change the badge from Jenkins to Travis? We test more browsers in Jenkins, see http://swarm.jquery.org/project/jquerycolor.

**Comment by raphamorim** [comment]
I can give a try. I'll send it in a separated PR.

**Comment by mgol** [comment]
@raphamorim I'm sorry, I don't understand. What I'm saying is that currently the badge shows Jenkins status and on Jenkins we test more browsers than on Travis so the Jenkins badge currently seems to provide a bigger picture than the Travis one.

Is there any reason to switch to Travis at this point? If not, there's no change to make here.

**Comment by raphamorim** [comment]
True @mgol.
Sorry I didn't understand at the first time. I agree I'm closing this PR in favor of Jenkins.

**Pull request closed without merging**
