### PR TITLE
Added browser support in readme

### PR DESCRIPTION
**Pull request by raphamorim**
Ref: https://github.com/jquery/jquery-color/issues/82

### CODE REVIEW

**Comment by gnarf** [comment]
:+1:

**Comment by mgol** [comment]
I'd add a note that it only supports those browsers the jQuery used supports (i.e. if you use it with jQuery 2, you won't have IE 6 support). Or is that obvious?

**Comment by gnarf** [comment]
Thanks for pushing me to update this, I made some changes and made my own commit, and put the browser support at the top.

**Comment by raphamorim** [comment]
:D :octocat:

**Pull request closed without merging**
