### PR TITLE
[WIP] Replace bower dependencies with npm packages

### PR DESCRIPTION
**Pull request by raphamorim**
Ref: #93

### CODE REVIEW

**Comment by raphamorim** [comment]
Hey @leobalter @gnarf @mgol 

I'm having a lot of problems to implement this PR.
One of these is: the lack of support for npm custom packages based on `url` or git` repos.
So implementations like: 

```json
"devDependencies": {
    "jquery-1.5.0": "http://code.jquery.com/jquery-1.5.js",
```

Doesn't work.

```json
"devDependencies": {
    "jquery-1.5.0": "git+https://github.com/jquery/jquery#1.5.0",
```

Doesn't work too :/
BTW: I'm using `3.5.3` as npm version.

**Comment by raphamorim** [comment]
I think one viable solution is to create a `preinstall` script to download all jquery-versions and place in `node_modules` or other place. 

What do you think?

**Comment by leobalter** [comment]
maybe you should copy these files from http://code.jquery.com

**Comment by mgol** [comment]
Since we keep those files in the repository anyway, I think a good solution would be to create a task that would get a jQuery version (`VERSION` below) as a parameter and would:

1. Check if https://unpkg.com/jquery@VERSION/dist/jquery.js exists; if not, print an error message & finish. Otherwise, go to the next step.
1. Create an `external/jquery-VERSION` directory.
1. Download https://unpkg.com/jquery@VERSION/dist/jquery.js & https://unpkg.com/jquery@3.1.1/LICENSE.txt & save both to `external/jquery-VERSION/`.

Once such a task exist, we could invoke it when we need a new version to be added. If we felt really ambitious we could even check for all versions newer than the newest ones on https://unpkg.com and download all the missing major/minor updates in their latest patch version, removing older patch releases (so e.g. 3.0.0 & 3.1.1 are fine but 3.1.0 should be removed).

We could then remove the whole Bower setup & the bowercopy task.

**Comment by raphamorim** [comment]
I'll proceed with @mgol (creating a node script to do it) 👍

**Comment by raphamorim** [comment]
@mgol I've checked and [unpkg](https://unpkg.com/) doesn't have all jQuery versions. 

jquery-color use for test the following jquery versions: `1.5.2`, `1.6.4`, `1.7.2`, `1.8.3`, `1.9.1`, `1.10.2`, `1.11.3`, `1.12.4`, `2.0.3`, `2.1.4`, `2.2.4`, `3.0.0` and `3.1.1`.

The Unpkg only have versions above of 1.11.3

**Comment by mgol** [comment]
unpkg is a CDN sharing npm packages and jQuery has been published to npm only since 1.11/2.1.

The old versions are already there, though, the script will download future versions which will all be on npm so this shouldn't be a problem.

**Comment by mgol** [comment]
@raphamorim will you have time to finish the PR?

**Comment by raphamorim** [comment]
Yeah, sorry for delaying it. I'll see it til tuesday :)

**Comment by raphamorim** [comment]
I was wondering if this PR is worth continuing. It would be valid to continue if we had followed the path using NPM or bower, but they [are not yet ripe for it](https://github.com/npm/npm/issues/5499).

But in the end, we'll exchange a download script for another download script.

**Comment by mgol** [comment]
@raphamorim 
> It would be valid to continue if we had followed the path using NPM or bower, but they [are not yet ripe for it](https://github.com/npm/npm/issues/5499).

I'd remove `yet` from this statement as npm doesn't plan to add this feature.

I think this PR would be worth to finish to get rid of the deprecated bower, though that's true that we'll have to maintain the download script ourselves then.

What do youy thinl?

**Comment by raphamorim** [comment]
Yeah, make sense to me.
Also: I'm closing this PR in favor of it.

**Comment by mgol** [comment]
> Also: I'm closing this PR in favor of it.

In favor of what?

**Comment by raphamorim** [comment]
Sorry, I expressed myself badly haha
In favor of:

> though that's true that we'll have to maintain the download script ourselves then.

**Pull request closed without merging**
