### PR TITLE
Do housekeeping + drop support for IE<9

### LINKED ISSUE #89: Drop IE 6 "fake alpha" support?
I think it's time, anyone agree?

cc @scottgonzalez for the UI perspective

### PR DESCRIPTION
**Pull request by mgol**
Reviewing individual commits might be easier than the whole.

Fixes #89

### CODE REVIEW

**Comment by mgol** [comment]
@leobalter What can I do about the BrowserStack auth error?

**Comment by gnarf** [comment]
Seems pretty good if we can fix the CI fail.

**Comment by gnarf** [comment]
Not that it matters a ton, but I would think that instead of `Core:` this should be `Color:` on 835abb62306f8175e6073ebda8c59ff7414cf89b ?

**Comment by mgol** [comment]
> Not that it matters a ton, but I would think that instead of `Core:` this should be `Color:` on 835abb62306f8175e6073ebda8c59ff7414cf89b ?

I used the component that's in [the `commitplease` list](https://github.com/jquery/jquery-color/blob/a64bdaec0124f81d278ad53ba74bb106b297572c/package.json#L49-L53). We'd need to change the list if you prefer different names.

**Comment by mgol** [comment]
I removed the outdated Core patch releases from available versions but I may add them back if you think it's worth it (I know UI tries to include everything).

**Comment by leobalter** [comment]
It looks good, I just have not idea what is happening with browserstack now.

**Comment by leobalter** [comment]
@mgol would you mind to rebase this branch? I believe this should be good now.

**Comment by leobalter** [comment]
yes, as I imagine, it works perfectly. +1 to merge when it's rebased.

**Comment by mgol** [comment]
Rebased. I also modified some middle commits (e.g. the one including jQuery 3.0.0-rc1 now includes 3.0.0 final & 3.1.1 instead).

IMO it all makes sense to land as separate commits. WDYT?

**Comment by leobalter** [comment]
GitHub swallowed to the void the comment I sent from email.

Yes I agree it makes sense to land with separate commits.

**Comment by leobalter** [comment]
I agree, that's why I asked you to rebate, so I can merge through GitHub
keeping track of the PR for all of them.

I'll merge as soon I get into a computer (currently on my phone)

**Pull request merged**
